# Generated by Django 4.0 on 2023-11-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('millennium', 'ミレニアム'), ('trinity', 'トリニティ'), ('gehenna', 'ゲヘナ'), ('abydos', 'アビドス'), ('hyakki', '百鬼夜行'), ('redwinter', 'レッドウィンター'), ('valkyrie', 'ヴァルキューレ'), ('srt', 'SRT'), ('sengaikyo', '山海経'), ('arius', 'アリウス')], max_length=50, verbose_name='カテゴリ')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('image', models.ImageField(upload_to='立ち絵', verbose_name='イメージ')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('birthday', models.DateTimeField(verbose_name='誕生日')),
                ('height', models.IntegerField(verbose_name='身長')),
                ('hobby', models.CharField(max_length=50, verbose_name='趣味')),
                ('voice', models.CharField(max_length=20, verbose_name='CV')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
    ]
