# Generated by Django 4.0 on 2023-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='birthday',
            field=models.DateField(verbose_name='誕生日'),
        ),
    ]
