# Generated by Django 4.0 on 2023-11-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapp', '0002_alter_characters_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='立ち絵'),
        ),
    ]
