# Generated by Django 4.0 on 2023-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapp', '0003_alter_characters_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='立ち絵'),
        ),
    ]
