# Generated by Django 4.0 on 2023-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strapp', '0006_bulletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
    ]
